# Generated by Django 4.0.3 on 2022-03-30 06:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_myuser_date_of_birth_alter_myuser_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_profile_image_handler),
        ),
    ]
